[2020-08-03T16:43:13.418] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"1"}
response time: 1596444193417
err name: SequelizeDatabaseError
err message: column "字段名（策划）" does not exist
err stack: SequelizeDatabaseError: column "字段名（策划）" does not exist
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-08-03T16:59:23.096] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"1","channel":"小米","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"1","gameid":"1"}
response time: 1596445163095
err name: TypeError
err message: Cannot read property 'path' of undefined
err stack: TypeError: Cannot read property 'path' of undefined
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:13:22)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at GmAnnouncementService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at GmAnnouncementService.createBulletin (E:\third\project\server\src\app\service\gm-announcement.js:134:32)
    at _callee$ (E:\third\project\server\src\app\controllers\/gm-announcement.js:15:53)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at create (E:\third\project\server\src\app\controllers\gm-announcement.js:97:24)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-08-03T16:59:43.116] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"1","channel":"小米","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596445183115
err name: TypeError
err message: Cannot read property 'path' of undefined
err stack: TypeError: Cannot read property 'path' of undefined
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:13:22)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at GmAnnouncementService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at GmAnnouncementService.createBulletin (E:\third\project\server\src\app\service\gm-announcement.js:134:32)
    at _callee$ (E:\third\project\server\src\app\controllers\/gm-announcement.js:15:53)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at create (E:\third\project\server\src\app\controllers\gm-announcement.js:97:24)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-08-03T17:00:24.089] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"1","channel":"小米","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596445224088
err name: TypeError
err message: Cannot read property 'file' of undefined
err stack: TypeError: Cannot read property 'file' of undefined
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:13:27)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at GmAnnouncementService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at GmAnnouncementService.createBulletin (E:\third\project\server\src\app\service\gm-announcement.js:135:32)
    at _callee$ (E:\third\project\server\src\app\controllers\/gm-announcement.js:15:53)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at create (E:\third\project\server\src\app\controllers\gm-announcement.js:96:24)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-08-03T17:00:50.263] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"1","channel":"小米","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596445250263
err name: TypeError
err message: Cannot read property 'images' of undefined
err stack: TypeError: Cannot read property 'images' of undefined
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:13:27)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at GmAnnouncementService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at GmAnnouncementService.createBulletin (E:\third\project\server\src\app\service\gm-announcement.js:135:32)
    at _callee$ (E:\third\project\server\src\app\controllers\/gm-announcement.js:15:53)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at create (E:\third\project\server\src\app\controllers\gm-announcement.js:96:24)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-08-03T17:01:05.012] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"1","channel":"小米","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596445265012
err name: ReferenceError
err message: path is not defined
err stack: ReferenceError: path is not defined
    at filePath (E:\third\project\server\src\app\service\/gm-announcement.js:18:19)
    at new Promise (<anonymous>)
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:15:25)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at GmAnnouncementService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at GmAnnouncementService.createBulletin (E:\third\project\server\src\app\service\gm-announcement.js:135:32)
    at _callee$ (E:\third\project\server\src\app\controllers\/gm-announcement.js:15:53)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at create (E:\third\project\server\src\app\controllers\gm-announcement.js:96:24)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
*************** error log end ***************

[2020-08-03T17:01:29.035] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"1","channel":"小米","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596445289035
err name: TypeError
err message: Cannot read property 'path' of undefined
err stack: TypeError: Cannot read property 'path' of undefined
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:14:22)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at GmAnnouncementService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at GmAnnouncementService.createBulletin (E:\third\project\server\src\app\service\gm-announcement.js:135:32)
    at _callee$ (E:\third\project\server\src\app\controllers\/gm-announcement.js:15:53)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at create (E:\third\project\server\src\app\controllers\gm-announcement.js:96:24)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-08-03T17:02:14.615] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"1","channel":"小米","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596445334615
err name: ReferenceError
err message: path is not defined
err stack: ReferenceError: path is not defined
    at filePath (E:\third\project\server\src\app\service\/gm-announcement.js:18:19)
    at new Promise (<anonymous>)
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:15:25)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at GmAnnouncementService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at GmAnnouncementService.createBulletin (E:\third\project\server\src\app\service\gm-announcement.js:135:32)
    at _callee$ (E:\third\project\server\src\app\controllers\/gm-announcement.js:15:53)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at create (E:\third\project\server\src\app\controllers\gm-announcement.js:96:24)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
*************** error log end ***************

[2020-08-03T17:02:16.115] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"1","channel":"小米","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596445336115
err name: ReferenceError
err message: path is not defined
err stack: ReferenceError: path is not defined
    at filePath (E:\third\project\server\src\app\service\/gm-announcement.js:18:19)
    at new Promise (<anonymous>)
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:15:25)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at GmAnnouncementService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at GmAnnouncementService.createBulletin (E:\third\project\server\src\app\service\gm-announcement.js:135:32)
    at _callee$ (E:\third\project\server\src\app\controllers\/gm-announcement.js:15:53)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at create (E:\third\project\server\src\app\controllers\gm-announcement.js:96:24)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
*************** error log end ***************

[2020-08-03T19:28:59.213] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"","channel":"小米,久游","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596454139212
err name: SequelizeDatabaseError
err message: malformed array literal: "小米,久游"
err stack: SequelizeDatabaseError: malformed array literal: "小米,久游"
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-08-03T19:34:12.912] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"","channel":"小米,久游,腾讯","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596454452912
err name: SequelizeDatabaseError
err message: malformed array literal: "小米,久游,腾讯"
err stack: SequelizeDatabaseError: malformed array literal: "小米,久游,腾讯"
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-08-03T19:50:44.689] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"","channel":"腾讯","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596455444689
err name: SequelizeDatabaseError
err message: malformed array literal: "腾讯"
err stack: SequelizeDatabaseError: malformed array literal: "腾讯"
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-08-03T19:51:11.283] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"","channel":"腾讯","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596455471282
err name: SequelizeDatabaseError
err message: syntax error at or near "腾讯"
err stack: SequelizeDatabaseError: syntax error at or near "腾讯"
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-08-03T19:56:39.432] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"","channel":"腾讯,小米,久游","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596455799431
err name: ReferenceError
err message: 腾讯 is not defined
err stack: ReferenceError: 腾讯 is not defined
    at eval (eval at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:30:35), <anonymous>:1:1)
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:30:35)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-08-03T19:57:14.697] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"","channel":"腾讯,小米,久游","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596455834697
err name: ReferenceError
err message: 腾讯 is not defined
err stack: ReferenceError: 腾讯 is not defined
    at eval (eval at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:30:35), <anonymous>:1:1)
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:30:35)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-08-03T19:57:38.277] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596444715293","stime":"","etime":"","plaform":"","channel":"腾讯,小米,久游","servername":"","interval":"","weights":"","title":"11111","a":"33333","text":"222221111","type":"2","gameid":"1"}
response time: 1596455858277
err name: ReferenceError
err message: 腾讯 is not defined
err stack: ReferenceError: 腾讯 is not defined
    at eval (eval at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:30:35), <anonymous>:1:1)
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:30:35)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-08-03T19:57:50.866] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596455861424","stime":"","etime":"","plaform":"1","channel":"小米,腾讯","servername":"","interval":"","weights":"","title":"111","a":"111","text":"","type":"2","gameid":"1"}
response time: 1596455870866
err name: ReferenceError
err message: 小米 is not defined
err stack: ReferenceError: 小米 is not defined
    at eval (eval at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:30:35), <anonymous>:1:1)
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:30:35)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-08-03T19:57:58.875] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596455861424","stime":"","etime":"","plaform":"1","channel":"小米,腾讯,久游","servername":"","interval":"","weights":"","title":"111","a":"111","text":"","type":"2","gameid":"1"}
response time: 1596455878875
err name: ReferenceError
err message: 小米 is not defined
err stack: ReferenceError: 小米 is not defined
    at eval (eval at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:30:35), <anonymous>:1:1)
    at _callee2$ (E:\third\project\server\src\app\service\/gm-announcement.js:30:35)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-08-03T20:55:15.858] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596459221826","stime":"Thu Jul 09 2020 00:00:00 GMT+0800 (中国标准时间)","etime":"Wed Aug 05 2020 00:00:00 GMT+0800 (中国标准时间)","plaform":"","channel":"久游","servername":"11111,1111,测试服3,测试服2,12,长澜？,1111111,123123,212,1,11,111,测试服1,123,","interval":"","weights":"","title":"","images":"","a":"","text":"","type":"1","gameid":"1"}
response time: 1596459315857
err name: SequelizeDatabaseError
err message: column "time_interval" of relation "gm_announcement" does not exist
err stack: SequelizeDatabaseError: column "time_interval" of relation "gm_announcement" does not exist
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-08-03T20:58:26.996] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596459221826","stime":"Thu Jul 09 2020 00:00:00 GMT+0800 (中国标准时间)","etime":"Wed Aug 05 2020 00:00:00 GMT+0800 (中国标准时间)","plaform":null,"channel":"久游","servername":"11111,1111,测试服3,测试服2,12,长澜？,1111111,123123,212,1,11,111,测试服1,123,","interval":null,"weights":null,"title":null,"images":null,"a":null,"text":null,"type":"1","gameid":"1"}
response time: 1596459506996
err name: SequelizeDatabaseError
err message: column "time_interval" of relation "gm_announcement" does not exist
err stack: SequelizeDatabaseError: column "time_interval" of relation "gm_announcement" does not exist
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-08-03T20:58:27.858] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"11596459221826","stime":"Thu Jul 09 2020 00:00:00 GMT+0800 (中国标准时间)","etime":"Wed Aug 05 2020 00:00:00 GMT+0800 (中国标准时间)","plaform":null,"channel":"久游","servername":"11111,1111,测试服3,测试服2,12,长澜？,1111111,123123,212,1,11,111,测试服1,123,","interval":null,"weights":null,"title":null,"images":null,"a":null,"text":null,"type":"1","gameid":"1"}
response time: 1596459507858
err name: SequelizeDatabaseError
err message: column "time_interval" of relation "gm_announcement" does not exist
err stack: SequelizeDatabaseError: column "time_interval" of relation "gm_announcement" does not exist
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-08-03T20:59:37.908] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"'11596459221826'","stime":"'Thu Jul 09 2020 00:00:00 GMT+0800 (中国标准时间)'","etime":"'Wed Aug 05 2020 00:00:00 GMT+0800 (中国标准时间)'","plaform":null,"channel":"'久游'","servername":"'11111,1111,测试服3,测试服2,12,长澜？,1111111,123123,212,1,11,111,测试服1,123,'","interval":null,"weights":null,"title":null,"images":null,"a":null,"text":null,"type":"'1'","gameid":"'1'"}
response time: 1596459577908
err name: SequelizeDatabaseError
err message: syntax error at or near ")"
err stack: SequelizeDatabaseError: syntax error at or near ")"
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-08-03T21:01:08.221] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"'11596459221826'","stime":"'Thu Jul 09 2020 00:00:00 GMT+0800 (中国标准时间)'","etime":"'Wed Aug 05 2020 00:00:00 GMT+0800 (中国标准时间)'","plaform":null,"channel":"'久游'","servername":"'11111,1111,测试服3,测试服2,12,长澜？,1111111,123123,212,1,11,111,测试服1,123,'","interval":null,"weights":null,"title":null,"images":null,"a":null,"text":null,"type":"'1'","gameid":"'1'"}
response time: 1596459668220
err name: SequelizeDatabaseError
err message: syntax error at or near ")"
err stack: SequelizeDatabaseError: syntax error at or near ")"
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-08-03T21:01:48.070] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"'11596459221826'","stime":"'Thu Jul 09 2020 00:00:00 GMT+0800 (中国标准时间)'","etime":"'Wed Aug 05 2020 00:00:00 GMT+0800 (中国标准时间)'","plaform":null,"channel":"'久游'","servername":"'11111,1111,测试服3,测试服2,12,长澜？,1111111,123123,212,1,11,111,测试服1,123,'","interval":null,"weights":null,"title":null,"images":null,"a":null,"text":null,"type":"'1'","gameid":"'1'"}
response time: 1596459708070
err name: SequelizeDatabaseError
err message: column "time_interval" of relation "gm_announcement" does not exist
err stack: SequelizeDatabaseError: column "time_interval" of relation "gm_announcement" does not exist
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-08-03T21:03:28.526] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"'11596459221826'","stime":"'Thu Jul 09 2020 00:00:00 GMT+0800 (中国标准时间)'","etime":"'Wed Aug 05 2020 00:00:00 GMT+0800 (中国标准时间)'","plaform":null,"channel":"'久游'","servername":"'11111,1111,测试服3,测试服2,12,长澜？,1111111,123123,212,1,11,111,测试服1,123,'","interval":null,"weights":null,"title":null,"images":null,"a":null,"text":null,"type":"'1'","gameid":"'1'"}
response time: 1596459808526
err name: SequelizeDatabaseError
err message: column "time_interval" of relation "gm_announcement" does not exist
err stack: SequelizeDatabaseError: column "time_interval" of relation "gm_announcement" does not exist
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-08-03T21:03:34.361] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"'11596459221826'","stime":"'Thu Jul 09 2020 00:00:00 GMT+0800 (中国标准时间)'","etime":"'Wed Aug 05 2020 00:00:00 GMT+0800 (中国标准时间)'","plaform":null,"channel":"'久游'","servername":"'11111,1111,测试服3,测试服2,12,长澜？,1111111,123123,212,1,11,111,测试服1,123,'","interval":null,"weights":null,"title":null,"images":null,"a":null,"text":null,"type":"'1'","gameid":"'1'"}
response time: 1596459814361
err name: SequelizeDatabaseError
err message: column "time_interval" of relation "gm_announcement" does not exist
err stack: SequelizeDatabaseError: column "time_interval" of relation "gm_announcement" does not exist
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-08-03T21:04:22.342] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"'11596459221826'","stime":"'Thu Jul 09 2020 00:00:00 GMT+0800 (中国标准时间)'","etime":"'Wed Aug 05 2020 00:00:00 GMT+0800 (中国标准时间)'","plaform":null,"channel":"'久游'","servername":"'11111,1111,测试服3,测试服2,12,长澜？,1111111,123123,212,1,11,111,测试服1,123,'","interval":null,"weights":null,"title":null,"images":null,"a":null,"text":null,"type":"'1'","gameid":"'1'"}
response time: 1596459862342
err name: SequelizeDatabaseError
err message: invalid input syntax for type timestamp: "Thu Jul 09 2020 00:00:00 GMT+0800 (中国标准时间)"
err stack: SequelizeDatabaseError: invalid input syntax for type timestamp: "Thu Jul 09 2020 00:00:00 GMT+0800 (中国标准时间)"
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-08-03T21:06:16.748] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"'11596459221826'","stime":"Thu Jul 09 2020 00:00:00 GMT+0800 (中国标准时间)","etime":"Wed Aug 05 2020 00:00:00 GMT+0800 (中国标准时间)","plaform":null,"channel":"'久游'","servername":"'11111,1111,测试服3,测试服2,12,长澜？,1111111,123123,212,1,11,111,测试服1,123,'","interval":null,"weights":null,"title":null,"images":null,"a":null,"text":null,"type":"'1'","gameid":"'1'"}
response time: 1596459976747
err name: SequelizeDatabaseError
err message: syntax error at or near "Jul"
err stack: SequelizeDatabaseError: syntax error at or near "Jul"
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-08-03T21:07:04.867] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"'11596459221826'","stime":"Thu Jul 09 2020 00:00:00 GMT+0800 (中国标准时间)","etime":"Wed Aug 05 2020 00:00:00 GMT+0800 (中国标准时间)","plaform":null,"channel":"'久游'","servername":"'11111,1111,测试服3,测试服2,12,长澜？,1111111,123123,212,1,11,111,测试服1,123,'","interval":null,"weights":null,"title":null,"images":null,"a":null,"text":null,"type":"'1'","gameid":"'1'"}
response time: 1596460024866
err name: SequelizeDatabaseError
err message: syntax error at or near "Jul"
err stack: SequelizeDatabaseError: syntax error at or near "Jul"
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-08-03T21:07:31.214] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"'11596459221826'","stime":"Thu Jul 09 2020 00:00:00 GMT+0800 (中国标准时间)","etime":"Wed Aug 05 2020 00:00:00 GMT+0800 (中国标准时间)","plaform":null,"channel":"'久游'","servername":"'11111,1111,测试服3,测试服2,12,长澜？,1111111,123123,212,1,11,111,测试服1,123,'","interval":null,"weights":null,"title":null,"images":null,"a":null,"text":null,"type":"'1'","gameid":"'1'"}
response time: 1596460051214
err name: SequelizeDatabaseError
err message: syntax error at or near "Jul"
err stack: SequelizeDatabaseError: syntax error at or near "Jul"
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-08-03T21:08:23.724] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/announcement/create
request client ip:  ::ffff:127.0.0.1
request body: 
{"bulletinid":"'11596459221826'","stime":"2020-07-09 00:00:00","etime":"2020-08-05 00:00:00","plaform":null,"channel":"'久游'","servername":"'11111,1111,测试服3,测试服2,12,长澜？,1111111,123123,212,1,11,111,测试服1,123,'","interval":null,"weights":null,"title":null,"images":null,"a":null,"text":null,"type":"'1'","gameid":"'1'"}
response time: 1596460103724
err name: SequelizeDatabaseError
err message: syntax error at or near "00"
err stack: SequelizeDatabaseError: syntax error at or near "00"
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

