[2020-07-23T13:32:02.595] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{}
response time: 1595482322595
err name: SequelizeDatabaseError
err message: column "[object Object]" does not exist
err stack: SequelizeDatabaseError: column "[object Object]" does not exist
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-07-23T13:40:12.171] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{}
response time: 1595482812170
err name: Error
err message: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
err stack: Error: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
    at NodeBufferReader.checkIndex (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:26:19)
    at NodeBufferReader.checkOffset (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:17:14)
    at NodeBufferReader.readData (E:\third\project\server\node_modules\jszip\lib\reader\NodeBufferReader.js:14:10)
    at NodeBufferReader.readString (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:75:49)
    at ZipEntries.isSignature (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:40:37)
    at ZipEntries.readEndOfCentral (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:165:35)
    at ZipEntries.load (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:256:14)
    at E:\third\project\server\node_modules\jszip\lib\load.js:49:20
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at XLSX.load (E:\third\project\server\node_modules\exceljs\lib\xlsx\xlsx.js:278:17)
    at XLSX.readFile (E:\third\project\server\node_modules\exceljs\lib\xlsx\xlsx.js:54:24)
*************** error log end ***************

[2020-07-23T13:40:22.390] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{}
response time: 1595482822390
err name: Error
err message: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
err stack: Error: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
    at NodeBufferReader.checkIndex (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:26:19)
    at NodeBufferReader.checkOffset (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:17:14)
    at NodeBufferReader.readData (E:\third\project\server\node_modules\jszip\lib\reader\NodeBufferReader.js:14:10)
    at NodeBufferReader.readString (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:75:49)
    at ZipEntries.isSignature (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:40:37)
    at ZipEntries.readEndOfCentral (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:165:35)
    at ZipEntries.load (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:256:14)
    at E:\third\project\server\node_modules\jszip\lib\load.js:49:20
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at XLSX.load (E:\third\project\server\node_modules\exceljs\lib\xlsx\xlsx.js:278:17)
    at XLSX.readFile (E:\third\project\server\node_modules\exceljs\lib\xlsx\xlsx.js:54:24)
*************** error log end ***************

[2020-07-23T14:00:20.379] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{}
response time: 1595484020378
err name: Error
err message: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
err stack: Error: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
    at NodeBufferReader.checkIndex (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:26:19)
    at NodeBufferReader.checkOffset (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:17:14)
    at NodeBufferReader.readData (E:\third\project\server\node_modules\jszip\lib\reader\NodeBufferReader.js:14:10)
    at NodeBufferReader.readString (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:75:49)
    at ZipEntries.isSignature (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:40:37)
    at ZipEntries.readEndOfCentral (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:165:35)
    at ZipEntries.load (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:256:14)
    at E:\third\project\server\node_modules\jszip\lib\load.js:49:20
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at XLSX.load (E:\third\project\server\node_modules\exceljs\lib\xlsx\xlsx.js:278:17)
    at XLSX.readFile (E:\third\project\server\node_modules\exceljs\lib\xlsx\xlsx.js:54:24)
*************** error log end ***************

[2020-07-23T14:00:32.809] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{}
response time: 1595484032809
err name: Error
err message: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
err stack: Error: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
    at NodeBufferReader.checkIndex (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:26:19)
    at NodeBufferReader.checkOffset (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:17:14)
    at NodeBufferReader.readData (E:\third\project\server\node_modules\jszip\lib\reader\NodeBufferReader.js:14:10)
    at NodeBufferReader.readString (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:75:49)
    at ZipEntries.isSignature (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:40:37)
    at ZipEntries.readEndOfCentral (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:165:35)
    at ZipEntries.load (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:256:14)
    at E:\third\project\server\node_modules\jszip\lib\load.js:49:20
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at XLSX.load (E:\third\project\server\node_modules\exceljs\lib\xlsx\xlsx.js:278:17)
    at XLSX.readFile (E:\third\project\server\node_modules\exceljs\lib\xlsx\xlsx.js:54:24)
*************** error log end ***************

[2020-07-23T14:03:12.864] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{}
response time: 1595484192863
err name: SequelizeDatabaseError
err message: invalid input syntax for type integer: "undefined"
err stack: SequelizeDatabaseError: invalid input syntax for type integer: "undefined"
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-07-23T14:04:53.348] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"undefined"}
response time: 1595484293348
err name: Error
err message: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
err stack: Error: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
    at NodeBufferReader.checkIndex (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:26:19)
    at NodeBufferReader.checkOffset (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:17:14)
    at NodeBufferReader.readData (E:\third\project\server\node_modules\jszip\lib\reader\NodeBufferReader.js:14:10)
    at NodeBufferReader.readString (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:75:49)
    at ZipEntries.isSignature (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:40:37)
    at ZipEntries.readEndOfCentral (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:165:35)
    at ZipEntries.load (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:256:14)
    at E:\third\project\server\node_modules\jszip\lib\load.js:49:20
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at XLSX.load (E:\third\project\server\node_modules\exceljs\lib\xlsx\xlsx.js:278:17)
    at XLSX.readFile (E:\third\project\server\node_modules\exceljs\lib\xlsx\xlsx.js:54:24)
*************** error log end ***************

[2020-07-23T14:04:59.422] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"undefined"}
response time: 1595484299422
err name: Error
err message: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
err stack: Error: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
    at NodeBufferReader.checkIndex (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:26:19)
    at NodeBufferReader.checkOffset (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:17:14)
    at NodeBufferReader.readData (E:\third\project\server\node_modules\jszip\lib\reader\NodeBufferReader.js:14:10)
    at NodeBufferReader.readString (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:75:49)
    at ZipEntries.isSignature (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:40:37)
    at ZipEntries.readEndOfCentral (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:165:35)
    at ZipEntries.load (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:256:14)
    at E:\third\project\server\node_modules\jszip\lib\load.js:49:20
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at XLSX.load (E:\third\project\server\node_modules\exceljs\lib\xlsx\xlsx.js:278:17)
    at XLSX.readFile (E:\third\project\server\node_modules\exceljs\lib\xlsx\xlsx.js:54:24)
*************** error log end ***************

[2020-07-23T14:24:05.597] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"undefined"}
response time: 1595485445596
err name: ReferenceError
err message: result is not defined
err stack: ReferenceError: result is not defined
    at _callee3$ (E:\third\project\server\src\app\service\/Character.js:257:10)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.uploadFile (E:\third\project\server\src\app\service\Character.js:283:28)
    at _callee3$ (E:\third\project\server\src\app\controllers\/Character.js:35:40)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at uploadFile (E:\third\project\server\src\app\controllers\Character.js:172:28)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-07-23T14:32:19.840] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"undefined"}
response time: 1595485939840
err name: TypeError
err message: The "listener" argument must be of type function. Received undefined
err stack: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received undefined
    at checkListener (events.js:111:11)
    at _addListener (events.js:348:3)
    at ReadStream.addListener (events.js:406:10)
    at ReadStream.on (_stream_readable.js:872:35)
    at _callee3$ (E:\third\project\server\src\app\service\/Character.js:235:23)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.uploadFile (E:\third\project\server\src\app\service\Character.js:272:28)
    at _callee3$ (E:\third\project\server\src\app\controllers\/Character.js:35:40)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at uploadFile (E:\third\project\server\src\app\controllers\Character.js:172:28)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
*************** error log end ***************

[2020-07-23T14:33:21.488] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"undefined"}
response time: 1595486001488
err name: TypeError
err message: The "listener" argument must be of type function. Received undefined
err stack: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received undefined
    at checkListener (events.js:111:11)
    at _addListener (events.js:348:3)
    at ReadStream.addListener (events.js:406:10)
    at ReadStream.on (_stream_readable.js:872:35)
    at _callee3$ (E:\third\project\server\src\app\service\/Character.js:235:23)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.uploadFile (E:\third\project\server\src\app\service\Character.js:273:28)
    at _callee3$ (E:\third\project\server\src\app\controllers\/Character.js:35:40)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at uploadFile (E:\third\project\server\src\app\controllers\Character.js:172:28)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
*************** error log end ***************

[2020-07-23T14:36:29.894] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"undefined"}
response time: 1595486189894
err name: TypeError
err message: The "listener" argument must be of type function. Received undefined
err stack: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received undefined
    at checkListener (events.js:111:11)
    at _addListener (events.js:348:3)
    at ReadStream.addListener (events.js:406:10)
    at ReadStream.on (_stream_readable.js:872:35)
    at _callee3$ (E:\third\project\server\src\app\service\/Character.js:235:10)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.uploadFile (E:\third\project\server\src\app\service\Character.js:272:28)
    at _callee3$ (E:\third\project\server\src\app\controllers\/Character.js:35:40)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at uploadFile (E:\third\project\server\src\app\controllers\Character.js:172:28)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
*************** error log end ***************

[2020-07-23T14:46:21.137] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"undefined"}
response time: 1595486781136
err name: ReferenceError
err message: result is not defined
err stack: ReferenceError: result is not defined
    at _callee4$ (E:\third\project\server\src\app\service\/Character.js:261:10)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.uploadFile (E:\third\project\server\src\app\service\Character.js:300:28)
    at _callee3$ (E:\third\project\server\src\app\controllers\/Character.js:35:40)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at uploadFile (E:\third\project\server\src\app\controllers\Character.js:172:28)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-07-23T15:04:50.885] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"undefined"}
response time: 1595487890885
err name: SequelizeDatabaseError
err message: operator does not exist: character varying = record
err stack: SequelizeDatabaseError: operator does not exist: character varying = record
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-07-23T15:05:40.052] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"undefined"}
response time: 1595487940051
err name: SequelizeDatabaseError
err message: invalid input syntax for type integer: "undefined"
err stack: SequelizeDatabaseError: invalid input syntax for type integer: "undefined"
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-07-23T15:06:03.211] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"1"}
response time: 1595487963211
err name: Error
err message: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
err stack: Error: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
    at NodeBufferReader.checkIndex (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:26:19)
    at NodeBufferReader.checkOffset (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:17:14)
    at NodeBufferReader.readData (E:\third\project\server\node_modules\jszip\lib\reader\NodeBufferReader.js:14:10)
    at NodeBufferReader.readString (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:75:49)
    at ZipEntries.isSignature (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:40:37)
    at ZipEntries.readEndOfCentral (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:165:35)
    at ZipEntries.load (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:256:14)
    at E:\third\project\server\node_modules\jszip\lib\load.js:49:20
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at XLSX.load (E:\third\project\server\node_modules\exceljs\lib\xlsx\xlsx.js:278:17)
    at XLSX.readFile (E:\third\project\server\node_modules\exceljs\lib\xlsx\xlsx.js:54:24)
*************** error log end ***************

[2020-07-23T15:06:14.468] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"1"}
response time: 1595487974468
err name: Error
err message: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
err stack: Error: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
    at NodeBufferReader.checkIndex (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:26:19)
    at NodeBufferReader.checkOffset (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:17:14)
    at NodeBufferReader.readData (E:\third\project\server\node_modules\jszip\lib\reader\NodeBufferReader.js:14:10)
    at NodeBufferReader.readString (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:75:49)
    at ZipEntries.isSignature (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:40:37)
    at ZipEntries.readEndOfCentral (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:165:35)
    at ZipEntries.load (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:256:14)
    at E:\third\project\server\node_modules\jszip\lib\load.js:49:20
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at XLSX.load (E:\third\project\server\node_modules\exceljs\lib\xlsx\xlsx.js:278:17)
    at XLSX.readFile (E:\third\project\server\node_modules\exceljs\lib\xlsx\xlsx.js:54:24)
*************** error log end ***************

[2020-07-23T15:06:24.746] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"1"}
response time: 1595487984746
err name: Error
err message: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
err stack: Error: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
    at NodeBufferReader.checkIndex (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:26:19)
    at NodeBufferReader.checkOffset (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:17:14)
    at NodeBufferReader.readData (E:\third\project\server\node_modules\jszip\lib\reader\NodeBufferReader.js:14:10)
    at NodeBufferReader.readString (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:75:49)
    at ZipEntries.isSignature (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:40:37)
    at ZipEntries.readEndOfCentral (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:165:35)
    at ZipEntries.load (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:256:14)
    at E:\third\project\server\node_modules\jszip\lib\load.js:49:20
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at XLSX.load (E:\third\project\server\node_modules\exceljs\lib\xlsx\xlsx.js:278:17)
    at XLSX.readFile (E:\third\project\server\node_modules\exceljs\lib\xlsx\xlsx.js:54:24)
*************** error log end ***************

[2020-07-23T15:06:57.109] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"1"}
response time: 1595488017109
err name: Error
err message: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
err stack: Error: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
    at NodeBufferReader.checkIndex (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:26:19)
    at NodeBufferReader.checkOffset (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:17:14)
    at NodeBufferReader.readData (E:\third\project\server\node_modules\jszip\lib\reader\NodeBufferReader.js:14:10)
    at NodeBufferReader.readString (E:\third\project\server\node_modules\jszip\lib\reader\DataReader.js:75:49)
    at ZipEntries.isSignature (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:40:37)
    at ZipEntries.readEndOfCentral (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:165:35)
    at ZipEntries.load (E:\third\project\server\node_modules\jszip\lib\zipEntries.js:256:14)
    at E:\third\project\server\node_modules\jszip\lib\load.js:49:20
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at XLSX.load (E:\third\project\server\node_modules\exceljs\lib\xlsx\xlsx.js:278:17)
    at XLSX.readFile (E:\third\project\server\node_modules\exceljs\lib\xlsx\xlsx.js:54:24)
*************** error log end ***************

[2020-07-23T15:17:07.051] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/character/uploadFile
request client ip:  ::ffff:127.0.0.1
request body: 
{"gameid":"1"}
response time: 1595488627049
err name: SequelizeDatabaseError
err message: column "字段名（策划）" does not exist
err stack: SequelizeDatabaseError: column "字段名（策划）" does not exist
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-07-23T16:26:47.501] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&regtime=&stime=&plaform=1&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","regtime":"","stime":"","plaform":"1","servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595492807500
err name: SyntaxError
err message: Unexpected end of JSON input
err stack: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Ta._callee2$ (E:\third\project\server\src\utils\/requests.js:94:15)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-07-23T16:27:01.329] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&regtime=&stime=&plaform=2&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","regtime":"","stime":"","plaform":"2","servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595492821329
err name: SyntaxError
err message: Unexpected end of JSON input
err stack: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Ta._callee2$ (E:\third\project\server\src\utils\/requests.js:94:15)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-07-23T16:27:02.361] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&regtime=&stime=&plaform=1&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","regtime":"","stime":"","plaform":"1","servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595492822361
err name: SyntaxError
err message: Unexpected end of JSON input
err stack: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Ta._callee2$ (E:\third\project\server\src\utils\/requests.js:94:15)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-07-23T16:27:28.183] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&regtime=&stime=&plaform=1&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","regtime":"","stime":"","plaform":"1","servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595492848182
err name: SyntaxError
err message: Unexpected end of JSON input
err stack: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Ta._callee2$ (E:\third\project\server\src\utils\/requests.js:94:21)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-07-23T16:28:23.408] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&regtime=&stime=&plaform=2&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","regtime":"","stime":"","plaform":"2","servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595492903408
err name: SyntaxError
err message: Unexpected end of JSON input
err stack: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Ta._callee2$ (E:\third\project\server\src\utils\/requests.js:95:21)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-07-23T16:29:00.134] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&regtime=&stime=&plaform=1&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","regtime":"","stime":"","plaform":"1","servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595492940133
err name: TypeError
err message: Cannot read property '0' of undefined
err stack: TypeError: Cannot read property '0' of undefined
    at Ta._callee2$ (E:\third\project\server\src\utils\/requests.js:95:16)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

