[2020-07-21T16:58:49.064] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/findServername
request client ip:  ::1
request query:  {}
response time: 1595321929064
err name: SequelizeDatabaseError
err message: syntax error at or near "where"
err stack: SequelizeDatabaseError: syntax error at or near "where"
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-07-21T16:58:58.316] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/findServername?gameid=1
request client ip:  ::1
request query:  {"gameid":"1"}
response time: 1595321938316
err name: SequelizeDatabaseError
err message: syntax error at or near "where"
err stack: SequelizeDatabaseError: syntax error at or near "where"
    at Query.formatError (E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:366:16)
    at E:\third\project\server\node_modules\sequelize\lib\dialects\postgres\query.js:72:18
    at tryCatcher (E:\third\project\server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\third\project\server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\third\project\server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\third\project\server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\third\project\server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\third\project\server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\third\project\server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\third\project\server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\third\project\server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
*************** error log end ***************

[2020-07-21T20:18:44.269] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&stime=&plaform=&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","stime":"","plaform":"","servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595333924269
err name: ReferenceError
err message: display is not defined
err stack: ReferenceError: display is not defined
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:124:10)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.queryByParms (E:\third\project\server\src\app\service\Character.js:111:30)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:16:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at queryCharacter (E:\third\project\server\src\app\controllers\Character.js:82:32)
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-07-21T20:18:47.680] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&regtime[]=2020-07-14T16:00:00.000Z&regtime[]=2020-08-12T16:00:00.000Z&stime=&plaform=&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","regtime[]":["2020-07-14T16:00:00.000Z","2020-08-12T16:00:00.000Z"],"stime":"","plaform":"","servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595333927680
err name: ReferenceError
err message: display is not defined
err stack: ReferenceError: display is not defined
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:124:10)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.queryByParms (E:\third\project\server\src\app\service\Character.js:111:30)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:16:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at queryCharacter (E:\third\project\server\src\app\controllers\Character.js:82:32)
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-07-21T20:19:09.419] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&stime=&plaform=&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","stime":"","plaform":"","servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595333949419
err name: ReferenceError
err message: display is not defined
err stack: ReferenceError: display is not defined
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:124:10)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.queryByParms (E:\third\project\server\src\app\service\Character.js:111:30)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:16:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at queryCharacter (E:\third\project\server\src\app\controllers\Character.js:82:32)
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-07-21T20:19:34.739] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&stime=&plaform=&channel[]=%E5%B0%8F%E7%B1%B3&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","stime":"","plaform":"","channel[]":"小米","servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595333974739
err name: ReferenceError
err message: display is not defined
err stack: ReferenceError: display is not defined
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:124:10)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.queryByParms (E:\third\project\server\src\app\service\Character.js:111:30)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:16:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at queryCharacter (E:\third\project\server\src\app\controllers\Character.js:82:32)
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-07-21T20:20:20.484] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&stime=&plaform=&channel[]=%E5%B0%8F%E7%B1%B3&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","stime":"","plaform":"","channel[]":"小米","servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595334020484
err name: ReferenceError
err message: display is not defined
err stack: ReferenceError: display is not defined
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:131:10)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.queryByParms (E:\third\project\server\src\app\service\Character.js:111:30)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:16:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at queryCharacter (E:\third\project\server\src\app\controllers\Character.js:82:32)
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-07-21T20:20:40.539] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&regtime[]=2020-06-30T16:00:00.000Z&regtime[]=2020-08-26T16:00:00.000Z&stime=&plaform=&channel[]=%E5%B0%8F%E7%B1%B3&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","regtime[]":["2020-06-30T16:00:00.000Z","2020-08-26T16:00:00.000Z"],"stime":"","plaform":"","channel[]":"小米","servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595334040539
err name: ReferenceError
err message: display is not defined
err stack: ReferenceError: display is not defined
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:131:10)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.queryByParms (E:\third\project\server\src\app\service\Character.js:111:30)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:16:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at queryCharacter (E:\third\project\server\src\app\controllers\Character.js:82:32)
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-07-21T20:22:05.318] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&regtime[]=2020-06-30T16:00:00.000Z&regtime[]=2020-08-26T16:00:00.000Z&stime=&plaform=&channel[]=%E5%B0%8F%E7%B1%B3&channel[]=%E8%85%BE%E8%AE%AF&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","regtime[]":["2020-06-30T16:00:00.000Z","2020-08-26T16:00:00.000Z"],"stime":"","plaform":"","channel[]":["小米","腾讯"],"servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595334125318
err name: ReferenceError
err message: display is not defined
err stack: ReferenceError: display is not defined
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:131:10)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.queryByParms (E:\third\project\server\src\app\service\Character.js:111:30)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:16:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at queryCharacter (E:\third\project\server\src\app\controllers\Character.js:82:32)
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-07-21T20:30:16.638] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&regtime[]=2020-06-30T16:00:00.000Z&regtime[]=2020-08-26T16:00:00.000Z&stime=&plaform=1&channel[]=%E5%B0%8F%E7%B1%B3&channel[]=%E4%B9%85%E6%B8%B8&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","regtime[]":["2020-06-30T16:00:00.000Z","2020-08-26T16:00:00.000Z"],"stime":"","plaform":"1","channel[]":["小米","久游"],"servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595334616637
err name: ReferenceError
err message: display is not defined
err stack: ReferenceError: display is not defined
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:131:10)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.queryByParms (E:\third\project\server\src\app\service\Character.js:120:30)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:16:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at queryCharacter (E:\third\project\server\src\app\controllers\Character.js:82:32)
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-07-21T20:31:06.530] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&regtime[]=2020-06-30T16:00:00.000Z&regtime[]=2020-08-26T16:00:00.000Z&stime=&plaform=1&channel[]=%E5%B0%8F%E7%B1%B3&channel[]=%E4%B9%85%E6%B8%B8&channel[]=%E8%85%BE%E8%AE%AF&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","regtime[]":["2020-06-30T16:00:00.000Z","2020-08-26T16:00:00.000Z"],"stime":"","plaform":"1","channel[]":["小米","久游","腾讯"],"servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595334666530
err name: ReferenceError
err message: display is not defined
err stack: ReferenceError: display is not defined
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:132:10)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.queryByParms (E:\third\project\server\src\app\service\Character.js:120:30)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:16:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at queryCharacter (E:\third\project\server\src\app\controllers\Character.js:82:32)
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-07-21T20:35:24.385] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&stime=&plaform=1&channel[]=%E5%B0%8F%E7%B1%B3&channel[]=%E4%B9%85%E6%B8%B8&channel[]=%E8%85%BE%E8%AE%AF&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","stime":"","plaform":"1","channel[]":["小米","久游","腾讯"],"servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595334924384
err name: ReferenceError
err message: display is not defined
err stack: ReferenceError: display is not defined
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:132:10)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.queryByParms (E:\third\project\server\src\app\service\Character.js:120:30)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:16:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at queryCharacter (E:\third\project\server\src\app\controllers\Character.js:82:32)
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-07-21T20:36:12.191] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&regtime[]=2020-07-06T16:00:00.000Z&regtime[]=2020-08-20T16:00:00.000Z&stime=&plaform=1&channel[]=%E5%B0%8F%E7%B1%B3&channel[]=%E4%B9%85%E6%B8%B8&channel[]=%E8%85%BE%E8%AE%AF&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","regtime[]":["2020-07-06T16:00:00.000Z","2020-08-20T16:00:00.000Z"],"stime":"","plaform":"1","channel[]":["小米","久游","腾讯"],"servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595334972191
err name: ReferenceError
err message: display is not defined
err stack: ReferenceError: display is not defined
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:132:10)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.queryByParms (E:\third\project\server\src\app\service\Character.js:120:30)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:15:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at queryCharacter (E:\third\project\server\src\app\controllers\Character.js:81:32)
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-07-21T20:38:32.491] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&regtime[]=2020-07-06T16:00:00.000Z&regtime[]=2020-08-20T16:00:00.000Z&stime[]=2020-06-28T16:00:00.000Z&stime[]=2020-08-09T16:00:00.000Z&plaform=1&channel[]=%E5%B0%8F%E7%B1%B3&channel[]=%E4%B9%85%E6%B8%B8&channel[]=%E8%85%BE%E8%AE%AF&servername=&banned_type=&banned_area=1&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","regtime[]":["2020-07-06T16:00:00.000Z","2020-08-20T16:00:00.000Z"],"stime[]":["2020-06-28T16:00:00.000Z","2020-08-09T16:00:00.000Z"],"plaform":"1","channel[]":["小米","久游","腾讯"],"servername":"","banned_type":"","banned_area":"1","page":"1","pagesize":"10","gameid":"1"}
response time: 1595335112490
err name: ReferenceError
err message: gameid is not defined
err stack: ReferenceError: gameid is not defined
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:154:105)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.queryByParms (E:\third\project\server\src\app\service\Character.js:122:30)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:15:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at queryCharacter (E:\third\project\server\src\app\controllers\Character.js:81:32)
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (E:\third\project\server\node_modules\koa-compose\index.js:42:32)
    at E:\third\project\server\node_modules\koa-mount\index.js:52:32
*************** error log end ***************

[2020-07-21T20:39:18.140] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&regtime[]=2020-07-06T16:00:00.000Z&regtime[]=2020-08-20T16:00:00.000Z&stime[]=2020-06-28T16:00:00.000Z&stime[]=2020-08-09T16:00:00.000Z&plaform=1&channel[]=%E5%B0%8F%E7%B1%B3&channel[]=%E4%B9%85%E6%B8%B8&channel[]=%E8%85%BE%E8%AE%AF&servername=&banned_type=&banned_area=2&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","regtime[]":["2020-07-06T16:00:00.000Z","2020-08-20T16:00:00.000Z"],"stime[]":["2020-06-28T16:00:00.000Z","2020-08-09T16:00:00.000Z"],"plaform":"1","channel[]":["小米","久游","腾讯"],"servername":"","banned_type":"","banned_area":"2","page":"1","pagesize":"10","gameid":"1"}
response time: 1595335158139
err name: ReferenceError
err message: display is not defined
err stack: ReferenceError: display is not defined
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:162:43)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-07-21T20:40:05.312] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&regtime[]=2020-07-06T16:00:00.000Z&regtime[]=2020-08-20T16:00:00.000Z&stime[]=2020-06-28T16:00:00.000Z&stime[]=2020-08-09T16:00:00.000Z&plaform=1&channel[]=%E5%B0%8F%E7%B1%B3&channel[]=%E4%B9%85%E6%B8%B8&servername=&banned_type=&banned_area=2&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","regtime[]":["2020-07-06T16:00:00.000Z","2020-08-20T16:00:00.000Z"],"stime[]":["2020-06-28T16:00:00.000Z","2020-08-09T16:00:00.000Z"],"plaform":"1","channel[]":["小米","久游"],"servername":"","banned_type":"","banned_area":"2","page":"1","pagesize":"10","gameid":"1"}
response time: 1595335205311
err name: ReferenceError
err message: display is not defined
err stack: ReferenceError: display is not defined
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:163:43)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-07-21T20:40:57.465] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=roleid&value=&regtime[]=2020-07-06T16:00:00.000Z&regtime[]=2020-08-20T16:00:00.000Z&stime[]=2020-06-28T16:00:00.000Z&stime[]=2020-08-09T16:00:00.000Z&plaform=1&channel[]=%E5%B0%8F%E7%B1%B3&servername=&banned_type=&banned_area=2&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"roleid","value":"","regtime[]":["2020-07-06T16:00:00.000Z","2020-08-20T16:00:00.000Z"],"stime[]":["2020-06-28T16:00:00.000Z","2020-08-09T16:00:00.000Z"],"plaform":"1","channel[]":"小米","servername":"","banned_type":"","banned_area":"2","page":"1","pagesize":"10","gameid":"1"}
response time: 1595335257465
err name: ReferenceError
err message: display is not defined
err stack: ReferenceError: display is not defined
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:163:43)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-07-21T20:44:12.339] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=account_id&value=&regtime[]=2020-07-21T16:00:00.000Z&regtime[]=2020-08-18T16:00:00.000Z&stime[]=2020-06-16T16:00:00.000Z&stime[]=2020-07-21T16:00:00.000Z&plaform=1&channel[]=%E5%B0%8F%E7%B1%B3&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"account_id","value":"","regtime[]":["2020-07-21T16:00:00.000Z","2020-08-18T16:00:00.000Z"],"stime[]":["2020-06-16T16:00:00.000Z","2020-07-21T16:00:00.000Z"],"plaform":"1","channel[]":"小米","servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595335452339
err name: TypeError
err message: value.map is not a function
err stack: TypeError: value.map is not a function
    at Function.byInArray (E:\third\project\server\src\app\service\/Character.js:54:144)
    at Function.tosql (E:\third\project\server\src\app\service\/Character.js:95:41)
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:151:31)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.queryByParms (E:\third\project\server\src\app\service\Character.js:113:30)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:15:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at queryCharacter (E:\third\project\server\src\app\controllers\Character.js:81:32)
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
*************** error log end ***************

[2020-07-21T20:44:26.616] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=account_id&value=&regtime[]=2020-07-21T16:00:00.000Z&regtime[]=2020-08-18T16:00:00.000Z&stime[]=2020-06-16T16:00:00.000Z&stime[]=2020-07-21T16:00:00.000Z&plaform=1&channel[]=%E5%B0%8F%E7%B1%B3&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"account_id","value":"","regtime[]":["2020-07-21T16:00:00.000Z","2020-08-18T16:00:00.000Z"],"stime[]":["2020-06-16T16:00:00.000Z","2020-07-21T16:00:00.000Z"],"plaform":"1","channel[]":"小米","servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595335466616
err name: TypeError
err message: value.map is not a function
err stack: TypeError: value.map is not a function
    at Function.byInArray (E:\third\project\server\src\app\service\/Character.js:54:144)
    at Function.tosql (E:\third\project\server\src\app\service\/Character.js:95:41)
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:151:31)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.queryByParms (E:\third\project\server\src\app\service\Character.js:113:30)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:15:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at queryCharacter (E:\third\project\server\src\app\controllers\Character.js:81:32)
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
*************** error log end ***************

[2020-07-21T20:45:14.715] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=account_id&value=&regtime[]=2020-07-21T16:00:00.000Z&regtime[]=2020-08-18T16:00:00.000Z&stime[]=2020-06-16T16:00:00.000Z&stime[]=2020-07-21T16:00:00.000Z&plaform=1&channel[]=%E4%B9%85%E6%B8%B8&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"account_id","value":"","regtime[]":["2020-07-21T16:00:00.000Z","2020-08-18T16:00:00.000Z"],"stime[]":["2020-06-16T16:00:00.000Z","2020-07-21T16:00:00.000Z"],"plaform":"1","channel[]":"久游","servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595335514714
err name: TypeError
err message: value.map is not a function
err stack: TypeError: value.map is not a function
    at Function.byInArray (E:\third\project\server\src\app\service\/Character.js:55:144)
    at Function.tosql (E:\third\project\server\src\app\service\/Character.js:96:41)
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:152:31)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.queryByParms (E:\third\project\server\src\app\service\Character.js:113:30)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:15:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at queryCharacter (E:\third\project\server\src\app\controllers\Character.js:81:32)
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
*************** error log end ***************

[2020-07-21T20:48:02.494] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=account_id&value=&regtime[]=2020-07-21T16:00:00.000Z&regtime[]=2020-08-18T16:00:00.000Z&stime[]=2020-06-16T16:00:00.000Z&stime[]=2020-07-21T16:00:00.000Z&plaform=1&channel[]=%E4%B9%85%E6%B8%B8&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"account_id","value":"","regtime[]":["2020-07-21T16:00:00.000Z","2020-08-18T16:00:00.000Z"],"stime[]":["2020-06-16T16:00:00.000Z","2020-07-21T16:00:00.000Z"],"plaform":"1","channel[]":"久游","servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595335682494
err name: TypeError
err message: value.map is not a function
err stack: TypeError: value.map is not a function
    at Function.byInArray (E:\third\project\server\src\app\service\/Character.js:55:144)
    at Function.tosql (E:\third\project\server\src\app\service\/Character.js:96:41)
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:152:31)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.queryByParms (E:\third\project\server\src\app\service\Character.js:113:30)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:15:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at queryCharacter (E:\third\project\server\src\app\controllers\Character.js:81:32)
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
*************** error log end ***************

[2020-07-21T20:48:47.393] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=account_id&value=&regtime[]=2020-07-21T16:00:00.000Z&regtime[]=2020-08-18T16:00:00.000Z&stime[]=2020-06-16T16:00:00.000Z&stime[]=2020-07-21T16:00:00.000Z&plaform=1&channel[]=%E4%B9%85%E6%B8%B8&servername=&banned_type=&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"account_id","value":"","regtime[]":["2020-07-21T16:00:00.000Z","2020-08-18T16:00:00.000Z"],"stime[]":["2020-06-16T16:00:00.000Z","2020-07-21T16:00:00.000Z"],"plaform":"1","channel[]":"久游","servername":"","banned_type":"","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595335727393
err name: TypeError
err message: value.map is not a function
err stack: TypeError: value.map is not a function
    at Function.byInArray (E:\third\project\server\src\app\service\/Character.js:55:144)
    at Function.tosql (E:\third\project\server\src\app\service\/Character.js:96:41)
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:152:31)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at CharacterService.<anonymous> (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at CharacterService.queryByParms (E:\third\project\server\src\app\service\Character.js:113:30)
    at _callee$ (E:\third\project\server\src\app\controllers\/Character.js:15:39)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at queryCharacter (E:\third\project\server\src\app\controllers\Character.js:81:32)
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at E:\third\project\server\node_modules\koa-router\lib\router.js:346:16
    at dispatch (E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at E:\third\project\server\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (E:\third\project\server\node_modules\koa-router\lib\router.js:351:31)
*************** error log end ***************

[2020-07-21T20:57:18.456] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=account_id&value=&regtime[]=2020-06-30T16:00:00.000Z&regtime[]=2020-08-18T16:00:00.000Z&plaform=2&channel=&servername=&banned_type=1&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"account_id","value":"","regtime[]":["2020-06-30T16:00:00.000Z","2020-08-18T16:00:00.000Z"],"plaform":"2","channel":"","servername":"","banned_type":"1","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595336238455
err name: undefined
err message: undefined
err stack: undefined
*************** error log end ***************

[2020-07-21T20:57:28.588] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=account_id&value=&plaform=2&channel=&servername=&banned_type=1&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"account_id","value":"","plaform":"2","channel":"","servername":"","banned_type":"1","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595336248588
err name: undefined
err message: undefined
err stack: undefined
*************** error log end ***************

[2020-07-21T20:57:49.229] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=account_id&value=&stime[]=2020-07-07T16:00:00.000Z&stime[]=2020-08-19T16:00:00.000Z&plaform=2&channel=&servername=&banned_type=1&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"account_id","value":"","stime[]":["2020-07-07T16:00:00.000Z","2020-08-19T16:00:00.000Z"],"plaform":"2","channel":"","servername":"","banned_type":"1","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595336269229
err name: undefined
err message: undefined
err stack: undefined
*************** error log end ***************

[2020-07-21T20:57:54.324] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=account_id&value=&plaform=2&channel=&servername=&banned_type=1&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"account_id","value":"","plaform":"2","channel":"","servername":"","banned_type":"1","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595336274324
err name: undefined
err message: undefined
err stack: undefined
*************** error log end ***************

[2020-07-21T20:58:50.228] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=account_id&value=&plaform=2&channel=&servername=&banned_type=1&banned_area=1&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"account_id","value":"","plaform":"2","channel":"","servername":"","banned_type":"1","banned_area":"1","page":"1","pagesize":"10","gameid":"1"}
response time: 1595336330227
err name: undefined
err message: undefined
err stack: undefined
*************** error log end ***************

[2020-07-21T20:58:58.353] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=account_id&value=&plaform=2&channel=&servername=&banned_type=1&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"account_id","value":"","plaform":"2","channel":"","servername":"","banned_type":"1","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595336338353
err name: undefined
err message: undefined
err stack: undefined
*************** error log end ***************

[2020-07-21T21:18:24.637] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=account_id&value=&plaform=&servername=&banned_type=1&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"account_id","value":"","plaform":"","servername":"","banned_type":"1","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595337504637
err name: undefined
err message: undefined
err stack: undefined
*************** error log end ***************

[2020-07-21T21:21:36.133] [ERROR] errorLogger - 
*************** error log start ***************
request method: GET
request originalUrl:  /api/character/query?key=account_id&value=&plaform=&channel[]=%E5%B0%8F%E7%B1%B3&servername=&banned_type=1&banned_area=&page=1&pagesize=10
request client ip:  ::ffff:127.0.0.1
request query:  {"key":"account_id","value":"","plaform":"","channel[]":"小米","servername":"","banned_type":"1","banned_area":"","page":"1","pagesize":"10","gameid":"1"}
response time: 1595337696133
err name: ReferenceError
err message: res is not defined
err stack: ReferenceError: res is not defined
    at _callee$ (E:\third\project\server\src\app\service\/Character.js:182:10)
    at tryCatch (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (E:\third\project\server\node_modules\regenerator-runtime\runtime.js:97:21)
    at asyncGeneratorStep (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\third\project\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

